name: Feature Request
description: Suggest an idea or enhancement.
labels: 'feature request'
body:
  - type: dropdown
    id: package
    attributes:
      label: Which SDK are you using?
      description: Please specify the exact SDK that you are using.
      options:
        - '@query-api/js'
        - '@query-api/vue'
        - '@query-api/nuxt'
        - '@query-api/react'
        - '@query-api/next'
  - type: textarea
    id: feature-description
    attributes:
      label: What are you trying to do?
      description: A description of what you want to happen.
      placeholder: 'I would like to see...'
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: What's your proposed solution?
      description:
        A description of how you think this could be solved, including any alternatives that you
        considered.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
